### ISSUE TITLE
Temperature?

### ISSUE THREAD

**Issue by rolikeusch** [claudiospizzi/node-red-contrib-mystrom-switch#1]
Would be great if you could also add the Temperature, the V2 switches also measure the Temperature ;) 

**V2 switch output:**
http://[Switch IP]/report
{
  "power": 35.804927825927734,
  "relay": true,
  "temperature": 21.369983673095703
}

**Comment by claudiospizzi** [comment]
Sure, makes sense. Check version 1.1.0 with the fix.

**Comment by rolikeusch** [comment]
It works! Thanks.
